package uChat;

public enum CommandCode {
	UNKNOW(0),
	SERVER_SYNC(1),				SERVER_SYNC_ACK(2),
	SERVER_GET_ROLES(3),		SERVER_GET_ROLES_ACK(4),
	SERVER_GET_USERS(5),		SERVER_GET_USERS_ACK(6),
	SERVER_ADD_USER(7), 		SERVER_ADD_USER_ACK(8),
	ROLE_GET_PERMISSIONS(9),	ROLE_GET_PERMISSIONS_ACK(10),
	ROLE_SET_PERMISSIONS(11),	ROLE_SET_PERMISSIONS_ACK(12),
	USER_GET_ROLES(13),			USER_GET_ROLES_ACK(14),
	USER_SET_ROLES(15),			USER_SET_ROLES_ACK(16),
	SERVER_DESTROY(17),			SERVER_DESTROY_ACK(18),
	SERVER_REMOVE_ROLE(19),		SERVER_REMOVE_ROLE_ACK(20),
	SERVER_LEAVE(21),			SERVER_LEAVE_ACK(22),
	CHANNEL_CREATE(23),			CHANNEL_CREATE_ACK(24),
	CHANNEL_LIST(25),			CHANNEL_LIST_ACK(26),
	CHANNEL_MESSAGE(27), 		CHANNEL_MESSAGE_ACK(28),
	CHANNEL_RECEIVE(29), 		CHANNEL_RECEIVE_ACK(30),
	CHANNEL_DESTROY(31), 		CHANNEL_DESTROY_ACK(32),
	SERVER_CREATE(33), 			SERVER_CREATE_ACK(34),
	SERVER_LIST(35), 			SERVER_LIST_ACK(36),
	FRIEND_MESSAGE(37),			FRIEND_MESSAGE_ACK(38),
	FRIEND_RECEIVE(39),			FRIEND_RECEIVE_ACK(40),
	FRIEND_LIST(41), 			FRIEND_LIST_ACK(42),
	FRIEND_ADD(43),				FRIEND_ADD_ACK(44),
	FRIEND_REMOVE(45), 			FRIEND_REMOVE_ACK(46),
	HEARTBEAT(47),				HEARTBEAT_ACK(48),
	
	EVENT_MESSAGE(49),
	EVENT_CHANNEL_CREATED(50),
	EVENT_CHANNEL_REMOVED(51),
	EVENT_USER_ADDED(52),
	EVENT_USER_REMOVED(53);
	
	private int value;
	private CommandCode(int value) {
		this.value = value;
	}
	
	public int getValue() { return value; }
	
	public static CommandCode fromValue(int value) {
		for (CommandCode code : values()) {
            if (code.getValue() == value) {
                return code;
            }
        }
        return UNKNOW;
	}
}
